### PR TITLE
M3 feature

### PR DESCRIPTION
**Pull request by SuyashFowdar**
In this feature, the following have been done:

- Added 'Add book' logic
- Added 'Remove book' logic
-  Mix the logic with the UI and make them work

Thank you.

### CODE REVIEW

**Review by krys2fa — CHANGES_REQUESTED** [review]
## Awesome work @krishnzzz 👏 
It was great that you implemented Hooks in your project. 💪 
Just a few more improvements to make to complete the project.
### Status: Changes Required ♻️ 
It looks like you missed a few requirements for the BookList component. See them below:
- [x] [REQUIRED] It should implement the `handleBookRemove` as seen in the [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/ImplementsRemoveBook.png).

- [x] [REQUIRED] It should pass the `handleRemoveBook` to the Book component as seen in the [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/ImplementsRemoveBook.png)

For the Book component,

- [x] [REQUIRED] It should attach the passed `handleRemoveBook` to on click event of `Remove book` button.

Please request another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hello  👋

**You've done pretty well here fixing a few issues raised in the previous review. 👌**

However, let's make this change.

- [ ] Kindly ensure you use the same eslint rules outlined [here](https://github.com/microverseinc/linters-config/blob/master/react-redux/.eslintrc.json). You seem to be using the previous rulesets. Please update it.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Comment by mikenath223** [comment]
### STATUS: INVALID PR ❌

This PR has been marked as invalid.

Reason: 
- Please ensure all linting issues are checked and fixed.

Feel free to contact me on slack(@michgolden) if you need further clarifications.

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Pull request merged**
